### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zhuchcn** [pypi/support#8498]
### PyPI Username

zhuchcn

### Reason for request

I am logging in from a new device. I know my password and have access to my email, but the verification email for unrecognized device never arrives. I have been trying since Dec 3, 2025.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @zhuchcn,

I would try to login again. There was a small bug that should be fixed now. Once you try to login, another "unrecognized" email should go out and once you click on the link in that email, you should be good to go.

**Comment by zhuchcn** [comment]
Hey, thanks for your response. But I still don't receive the "unrecognized device" email. I have  tried multiple times in the last 4 days. Also verified that they are not in the spam.

**Comment by zhuchcn** [comment]
@Thespi-Brain Just an update: still not receiving the "unrecognized" email.
