### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by theneelshah** [pypi/support#8523]
### PyPI Username

amazon-neptune

### Reason for request

I tried logging into from a recognized device, I still can't login to my account. I know my password and have access to my email, but the verification email for unrecognized device never arrives. 

Also, I had a few recovery codes, I tried all but 2 of them. All of them just say that the device is still unrecognized and doesn't let me login

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @theneelshah,

Try clicking on the link and it should let you log in. If not, try to log in to PyPI, and you should receive another "unrecognized device" verification email. There was a small bug before but it has been resolved, but you should be able to login again. Let us know if you are still having issues.

**Comment by theneelshah** [comment]
Hi @Thespi-Brain, Thanks for your response!

I still see the "unrecognized device" on the login page. Didn't receive an email in one of the associated email addresses. Can you please trigger the verification email from your end to adirame@amazon.com [which is one of the associated addresses to the account].

**Comment by Thespi-Brain** [comment]
Hello @theneelshah,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues.
